"""Protocol smoke test for the stitch-bridges service plugin.

Generated by ``stitch_plugin_tools new``. Exercises the full plugin
lifecycle via the ``stitch_plugin_testing`` harness: spawn → init →
ping → health_check command → close.

Run from the package root::

    pytest tests/test_plugin_protocol.py -q --timeout=60
"""

from __future__ import annotations

from pathlib import Path

import pytest

try:
    from stitch_plugin_testing import make_plugin_client
except ImportError:
    pytest.skip(
        "stitch_plugin_testing not importable — run "
        "`pip install -e python/` from the repo root",
        allow_module_level=True,
    )

# Package dir = parent of this tests/ dir (holds plugin.json + stitch_bridges/).
_PACKAGE_DIR = Path(__file__).resolve().parent.parent


def test_plugin_protocol_roundtrip() -> None:
    """init → ping → echo → close against the scaffolded plugin."""
    with make_plugin_client(_PACKAGE_DIR) as client:
        # init handshake completed by make_plugin_client.
        init = client.init_result
        assert isinstance(init, dict)
        assert init["plugin_id"] == "stitch-bridges"

        # ping succeeds.
        assert client.ping() is True

        # health_check command reports the bridge runtime.
        result = client.call("health_check", {})
        assert result["ok"] is True
